name: Publish Docker Image

on:
  release:
    types: [published]

jobs:
  publish-docker-image:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get repository owner
        uses: ASzc/change-string-case-action@v6
        id: repo-owner
        with:
          string: ${{ github.repository_owner }}

      - name: Get crate version
        uses: colathro/crate-version@1.0.0
        id: crate-version
        with:
          file: ./Cargo.toml

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/${{ steps.repo-owner.outputs.lowercase }}/proxy-scraper-checker:${{ steps.crate-version.outputs.version }}
            ghcr.io/${{ steps.repo-owner.outputs.lowercase }}/proxy-scraper-checker:latest
